/* Automatically generated from o-help.txt */
#ifndef OCHELP_DATA_H
#define OCHELP_DATA_H

const char *help_text = 
    "===============================\n"
    "\n"
    "OCTA CORE UTILS HELP DOCUMENTATION\n"
    "\n"
    "===============================\n"
    "Copyright (c) 2026 YohanesOktanio. All rights reserved.\n"
    "\n"
    "\n"
    "cat         - Concatenate and print files.\n"
    "              Usage: cat <file...>\n"
    "\n"
    "clear       - Clear the screen.\n"
    "              Usage: clear\n"
    "\n"
    "cp          - Copy a file.\n"
    "              Usage: cp <source> <destination>\n"
    "\n"
    "df          - Disk free space.\n"
    "              Usage: df [path]\n"
    "\n"
    "du          - Disk usage.\n"
    "              Usage: du [path]\n"
    "\n"
    "env         - List environment variables.\n"
    "              Usage: env\n"
    "\n"
    "ls          - List files.\n"
    "              Usage: ls [-a] [-l] [-ll]\n"
    "\n"
    "mv          - Move/rename a file.\n"
    "              Usage: mv <source> <destination>\n"
    "\n"
    "notify      - Show a message box.\n"
    "              Usage: notify [-i|-w|-e|-q] <message>\n"
    "\n"
    "open        - Open a file, URL, or folder.\n"
    "              Usage: open <file|url|folder>\n"
    "\n"
    "pwd         - Print working directory.\n"
    "              Usage: pwd\n"
    "\n"
    "rm          - Remove files/directories.\n"
    "              Usage: rm [-r] [-f] file\n"
    "\n"
    "rmdir       - Remove directory.\n"
    "              Usage: rmdir <directory>\n"
    "\n"
    "sleep       - Sleep for a given number of seconds.\n"
    "              Usage: sleep <seconds>\n"
    "\n"
    "sptest      - Test speakers (Left and Right).\n"
    "              Usage: sptest\n"
    "\n"
    "stat        - Display file status.\n"
    "              Usage: stat <file>\n"
    "\n"
    "touch       - Create an empty file or update timestamp.\n"
    "              Usage: touch <file>\n"
    "\n"
    "tree        - Display directory tree.\n"
    "              Usage: tree [path]\n"
    "\n"
    "which       - Locate a program in PATH.\n"
    "              Usage: which <program>\n"
    "\n"
    "whoami      - Print current user.\n"
    "              Usage: whoami\n"
    "\n"
    "xbrightnes  - Set monitor brightness (if supported).\n"
    "              Usage: brightness <0-100>\n"
    "\n"
    "yes         - Print \"y\" or a string repeatedly.\n"
    "              Usage: yes [string]\n"
    "\n"
    ;

#endif
